version: '3.8'

services:
  redis:
    image: redis
    container_name: redis_shortener
    ports:
      - "6379:6379"

  weatherlite-api:
    build: .
    container_name: linkshortener-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
