name: Build .NET Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Твоя версия .NET

    - name: Restore dependencies
      run: dotnet restore src/PS.LinkShortenerMinimalApi/PS.LinkShortenerMinimalApi.Web

    - name: Build
      run: dotnet build src/PS.LinkShortenerMinimalApi/PS.LinkShortenerMinimalApi.Web --no-restore --configuration Release

    - name: Build Docker image
      run: docker build -t linkshortener:latest ./src/PS.LinkShortenerMinimalApi/PS.LinkShortenerMinimalApi.Web

